import json
import datetime
import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from reportlab.platypus import Paragraph, Spacer

def load_uptime_data():
    try:
        with open("docs/uptime_data.json", "r") as f:
            return json.load(f)
    except FileNotFoundError:
        print("No uptime data found! Run health_check.py first!")
        return None

def calculate_metrics(uptime_data):
    metrics = []
    for service_name, data in uptime_data.items():
        if data["total_checks"] > 0:
            uptime_pct = (data["successful_checks"] / data["total_checks"] * 100)
            sla_met = "YES" if uptime_pct >= 99.9 else "NO"
            metrics.append({
                "service": service_name,
                "uptime": f"{uptime_pct:.1f}%",
                "total_checks": data["total_checks"],
                "successful": data["successful_checks"],
                "failed": data["failed_checks"],
                "status": data["last_status"],
                "sla_met": sla_met,
                "downtime_events": len(data["downtime_events"])
            })
    return metrics

def generate_pdf_report(metrics):
    os.makedirs("docs", exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"docs/SLA_Report_{timestamp}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Application Health Monitor - SLA Report", styles["Title"]))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    story.append(Spacer(1, 20))

    story.append(Paragraph("Executive Summary", styles["Heading1"]))
    story.append(Spacer(1, 12))

    total_services = len(metrics)
    healthy = len([m for m in metrics if m["status"] == "UP"])
    sla_met = len([m for m in metrics if m["sla_met"] == "YES"])

    summary_data = [
        ["Metric", "Value"],
        ["Total Services Monitored", str(total_services)],
        ["Services Currently UP", str(healthy)],
        ["Services Meeting SLA", str(sla_met)],
        ["SLA Target", "99.9% uptime"],
    ]

    summary_table = Table(summary_data, colWidths=[300, 200])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("BACKGROUND", (0, 1), (-1, -1), colors.lightblue),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("Detailed Service Metrics", styles["Heading1"]))
    story.append(Spacer(1, 12))

    detail_data = [["Service", "Uptime %", "Checks", "Passed", "Failed", "SLA Met"]]
    for m in metrics:
        detail_data.append([
            m["service"],
            m["uptime"],
            str(m["total_checks"]),
            str(m["successful"]),
            str(m["failed"]),
            m["sla_met"]
        ])

    detail_table = Table(detail_data, colWidths=[150, 70, 60, 60, 60, 80])
    detail_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("BACKGROUND", (0, 1), (-1, -1), colors.lightgrey),
    ]))
    story.append(detail_table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("Downtime Events", styles["Heading1"]))
    story.append(Spacer(1, 12))

    incident_data = [["Service", "Downtime Events"]]
    for m in metrics:
        incident_data.append([m["service"], str(m["downtime_events"])])

    incident_table = Table(incident_data, colWidths=[300, 200])
    incident_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("BACKGROUND", (0, 1), (-1, -1), colors.lightyellow),
    ]))
    story.append(incident_table)
    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by App Health Monitor - Built by Chandu", styles["Normal"]))

    doc.build(story)
    print(f"PDF Report generated: {filename}")
    return filename

if __name__ == '__main__':
    print("Generating SLA Report...")
    uptime_data = load_uptime_data()
    if uptime_data:
        metrics = calculate_metrics(uptime_data)
        filename = generate_pdf_report(metrics)
        print(f"Report saved to: {filename}")